# Generated by Django 5.1 on 2024-08-14 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mangas_all_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangas',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='mangas',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mangas',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
