# Generated by Django 5.1 on 2024-08-14 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chapters_options_alter_mangas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'ordering': ['created_date', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='mangas',
            options={'ordering': ['-created_date', '-updated']},
        ),
        migrations.AddField(
            model_name='chapters',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mangas',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
