# Generated by Django 5.1 on 2024-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chapters_options_alter_mangas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='chapters',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
